// create the action types for the home
export const GET_CHANNELS = 'GET_CHANNELS';
export const GET_RECOMMENDED_VIDEOS = 'GET_RECOMMENDED_VIDEOS';
export const GET_ARCHIVED_VIDEOS = 'GET_ARCHIVED_VIDEOS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CHANGE_LIVETV_NAVIGATION_STATUS='CHANGE_LIVETV_NAVIGATION_STATUS'
export const GET_HOME_SETTINGS='GET_HOME_SETTINGS'
export const CHANGE_FAVOURITE_CHANNELS='CHANGE_FAVOURITE_CHANNELS'
export const GET_USER_PROFILE_SETTINGS='GET_USER_PROFILE_SETTINGS'
export const GET_PACKAGES='GET_PACKAGES'